# Utilise une image Node.js officielle
FROM node:20-alpine

# Définit le répertoire de travail
WORKDIR /app

# Copie les fichiers de configuration de npm
COPY package.json package-lock.json* ./

# Installe toutes les dépendances
RUN npm install

# Copie le reste des fichiers du projet
COPY . .

# Expose le port 5173
EXPOSE 5173

# Lance l'application
CMD ["npm", "run", "dev"]
