global:
  scrape_interval: 15s # How often Prometheus asks for data

scrape_configs:
  # Prometheus monitoring its own internal health
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Prometheus scraping the Node Exporter container
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']

  # Prometheus scraping the database container through the postgres-exporter
  - job_name: 'database'
    static_configs:
      - targets: ['postgres-exporter:9187']