apiVersion: 1
groups:
    - orgId: 1
      name: critical
      folder: Critical alerts
      interval: 1m
      rules:
        - uid: bg052ehty7fggb
          title: Event Loop Starvation
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: nodejs_eventloop_lag_p99_seconds * 1000
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 100
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ad84wt6
          panelId: 6
          noDataState: KeepLast
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: ad84wt6
            __panelId__: "6"
          isPaused: false
          notification_settings:
            receiver: discord-bot
        - uid: eg053nz4hq5moa
          title: Nginx Proxy Down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: nginx_up
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: eq
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ad84wt6
          panelId: 7
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: ad84wt6
            __panelId__: "7"
          isPaused: false
          notification_settings:
            receiver: discord-bot
        - uid: dg053qw2g5kowb
          title: Database Down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: pg_up
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: eq
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ad84wt6
          panelId: 7
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: ad84wt6
            __panelId__: "7"
          isPaused: false
          notification_settings:
            receiver: discord-bot
        - uid: bg053uhvpotfke
          title: NestJS Backend Down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: up{job="backend"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: eq
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ad84wt6
          panelId: 7
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: ad84wt6
            __panelId__: "7"
          isPaused: false
          notification_settings:
            receiver: discord-bot
    - orgId: 1
      name: warning
      folder: Warning alerts
      interval: 1m
      rules:
        - uid: cg0522ov937y8f
          title: Database Connection Saturation
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: pg_stat_database_numbackends{datname!~"postgres|template.*"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ad84wt6
          panelId: 3
          noDataState: NoData
          execErrState: Error
          annotations:
            __dashboardUid__: ad84wt6
            __panelId__: "3"
          isPaused: false
          notification_settings:
            receiver: empty
        - uid: bg05284rzeeioa
          title: Backend Memory Exhaustion
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: process_resident_memory_bytes{job="backend"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 4.02653184e+08
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ad84wt6
          panelId: 10
          noDataState: KeepLast
          execErrState: Error
          annotations:
            __dashboardUid__: ad84wt6
            __panelId__: "10"
          isPaused: false
          notification_settings:
            receiver: empty
        - uid: fg053yrdrk3y8e
          title: Active connections alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: nginx_connections_active
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 100
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ad84wt6
          panelId: 12
          noDataState: NoData
          execErrState: Error
          annotations:
            __dashboardUid__: ad84wt6
            __panelId__: "12"
          isPaused: false
          notification_settings:
            receiver: empty
